exports.VIEW_MODE = {
    SINGLE: "VIEW_MODE_SINGLE",
    DOUBLE: "VIEW_MODE_DOUBLE",
    WATERFALL: "VIEW_MODE_WATERFALL"
}

exports.READ_MODE = {
    TRADITION: "READ_MODE_TRADITION",
    MORDEN: "READ_MODE_MORDEN"
}